from enum import Enum

class EventType(str, Enum):
    MARKET_PRICE_UPDATED = "MARKET_PRICE_UPDATED"
    BACKTEST_COMPLETED = "BACKTEST_COMPLETED"
    STRATEGY_GENERATED = "STRATEGY_GENERATED"
    LEADERBOARD_UPDATED = "LEADERBOARD_UPDATED"
    NEWS_COLLECTED = "NEWS_COLLECTED"
    SENTIMENT_ANALYZED = "SENTIMENT_ANALYZED"
